name: ci

on:
  push:
    branches:
      - master

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 'Check out your Hugo site'
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: 'Install Hugo'
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true

      - name: 'Build site'
        run: |
          hugo --gc --minify --cleanDestinationDir --baseURL="https://bw.enabc.net/"

      - name: 'Deploy to GitHub Pages'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_orphan: true
          cname: bw.enabc.net
